version: '3'

services:
  app:
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    networks:
      - xinghai-network

  db:
    image: mariadb:10.9.1-rc-jammy
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/var/lib/mariadb
    networks:
      - xinghai-network

  webserver:
    image: nginx:1.23.1-alpine
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - xinghai-network

volumes:
  dbdata:

networks:
  xinghai-network:
    driver: bridge
